server:
  port: 8091

ltzf:
  sdk:
    config:
      enabled: true
      app_id: 1107245
      merchant_id: 1676472264
      partner_key: dedba96426f8f9ca3ad9738f55f3399a

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml